In [298]:
# %pip install pandas 
import pandas as pd

dataset = pd.read_csv('CPITimeSeries.csv',low_memory=False)

In [299]:
dataset.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Attribute,1950M1,1950M2,1950M3,1950M4,1950M5,...,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8,Common Reference Period,Unnamed: 878
0,Brazil,223,"Consumer Price Index, All items, Percentage ch...",PCPI_PC_PP_PT,Value,NaN,NaN,NaN,NaN,NaN,...,0.540029150136277,1.01006161132049,1.62005007047194,1.06001808126436,0.470007269445767,0.670057758760498,-0.680003407761961,NaN,NaN,NaN
1,Brazil,223,"Consumer Price Index, All items, Percentage ch...",PCPI_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,...,10.3794248442458,10.5436617263354,11.2994121295852,12.1316302169067,11.731212845584,11.886869625198,10.0694033168709,NaN,NaN,NaN
2,Brazil,223,Communication,PCPIEC_IX,Value,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993M12,NaN
3,Brazil,223,Communication,PCPIEC_IX,Reference Period,NaN,NaN,NaN,NaN,NaN,...,1993M12,1993M12,1993M12,1993M12,1993M12,1993M12,1993M12,NaN,NaN,NaN
4,Brazil,223,Clothing and footwear,PCPIA_IX,Value,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993M12,NaN

In [300]:
# Filter the dataset to keep only rows where "Attribute" is "Value"
dataset = dataset[dataset['Attribute'] == 'Value']
dataset.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Attribute,1950M1,1950M2,1950M3,1950M4,1950M5,...,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8,Common Reference Period,Unnamed: 878
0,Brazil,223,"Consumer Price Index, All items, Percentage ch...",PCPI_PC_PP_PT,Value,NaN,NaN,NaN,NaN,NaN,...,0.540029150136277,1.01006161132049,1.62005007047194,1.06001808126436,0.470007269445767,0.670057758760498,-0.680003407761961,NaN,NaN,NaN
1,Brazil,223,"Consumer Price Index, All items, Percentage ch...",PCPI_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,...,10.3794248442458,10.5436617263354,11.2994121295852,12.1316302169067,11.731212845584,11.886869625198,10.0694033168709,NaN,NaN,NaN
2,Brazil,223,Communication,PCPIEC_IX,Value,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993M12,NaN
4,Brazil,223,Clothing and footwear,PCPIA_IX,Value,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993M12,NaN
6,France,132,"Restaurants and hotels, Weight",PCPIRE_WT,Value,NaN,NaN,NaN,NaN,NaN,...,66,66,66,66,66,66,66,66,NaN,NaN

In [301]:
# Select only the columns whose names follow the "YYYYM#" format,
# meaning 4 digits for the year + 'M' + the month number.
year_columns = dataset.columns[dataset.columns.str.match(r'^\d{4}M\d+$')]
year_columns

# Extract only the years (the first 4 digits of the column names)
years = year_columns.str[:4].astype(int)

# Show only the years that are out of order
# diff() < 0 indicates a decrease, meaning the order is not increasing
out_of_order_years = years[years.diff().fillna(1) < 0]

In [302]:
# Extract year and month from the column names
year_month = year_columns.str.extract(r'(?P<Year>\d{4})M(?P<Month>\d{1,2})')
year_month['Year'] = year_month['Year'].astype(int)
year_month['Month'] = year_month['Month'].astype(int)

# Check for months that are out of order within each year
# diff() < 0 indicates a decrease in the sequence
months_out_of_order = year_month.groupby('Year')['Month'].apply(lambda x: x[x.diff().fillna(1) < 0])

print("Months out of order by year:")
print(months_out_of_order)

Months out of order by year:
Series([], Name: Month, dtype: int64)

In [303]:
# Keep only the columns with year >= 1990
year_columns_1990_onwards = year_columns[year_columns.str[:4].astype(int) >= 1990]

# Display the filtered columns
year_columns_1990_onwards

Index(['1990M1', '1990M2', '1990M3', '1990M4', '1990M5', '1990M6', '1990M7',
       '1990M8', '1990M9', '1990M10',
       ...
       '2021M11', '2021M12', '2022M1', '2022M2', '2022M3', '2022M4', '2022M5',
       '2022M6', '2022M7', '2022M8'],
      dtype='str', length=392)

In [304]:
year_filter_data = dataset[["Country Name","Indicator Name", "Indicator Code",] + list(year_columns_1990_onwards)]
year_filter_data.head()

,Country Name,Indicator Name,Indicator Code,1990M1,1990M2,1990M3,1990M4,1990M5,1990M6,1990M7,...,2021M11,2021M12,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8
0,Brazil,"Consumer Price Index, All items, Percentage ch...",PCPI_PC_PP_PT,67.5500201585559,75.7299998872637,82.3899860535296,15.5199783192206,7.59000524605285,11.7500127582383,12.920002092382,...,0.950069037020781,0.729958243425856,0.540029150136277,1.01006161132049,1.62005007047194,1.06001808126436,0.470007269445767,0.670057758760498,-0.680003407761961,NaN
1,Brazil,"Consumer Price Index, All items, Percentage ch...",PCPI_PC_CP_A_PT,2426.12066594988,3701.29520297563,6390.52873938333,6821.30914769282,6214.99288949151,5385.4302602777,4749.02826788979,...,10.7385009076792,10.0609827374433,10.3794248442458,10.5436617263354,11.2994121295852,12.1316302169067,11.731212845584,11.886869625198,10.0694033168709,NaN
2,Brazil,Communication,PCPIEC_IX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Brazil,Clothing and footwear,PCPIA_IX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,France,"Restaurants and hotels, Weight",PCPIRE_WT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59.9,59.9,66,66,66,66,66,66,66,66

In [305]:
# Filter year_filter_data to keep only rows where Indicator Code is 'PCPI_IX'
pcpi_ix_data = year_filter_data[year_filter_data["Indicator Code"] == "PCPI_IX"]
pcpi_ix_data.head()

,Country Name,Indicator Name,Indicator Code,1990M1,1990M2,1990M3,1990M4,1990M5,1990M6,1990M7,...,2021M11,2021M12,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8
17,Brazil,"Consumer Price Index, All items",PCPI_IX,0.005410857,0.009508499,0.01734255,0.02003411,0.0215547,0.02408738,0.02719947,...,6075.69,6120.04,6153.09,6215.24,6315.93,6382.88,6412.88,6455.85,6411.95,NaN
30,France,"Consumer Price Index, All items",PCPI_IX,66.42,66.56,66.72,67.09,67.19,67.18,67.2,...,107.64,107.85,108.12,108.94,110.49,110.97,111.72,112.55,112.87,113.29
104,Bulgaria,"Consumer Price Index, All items",PCPI_IX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7659.2699399122,7728.99879117314,7841.08640403034,7954.55523691129,8131.17796924526,8331.52722236692,8432.65279081599,8506.69398844988,8601.91208943529,8702.17132815588
154,Honduras,"Consumer Price Index, All items",PCPI_IX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,365,368.5,373,374.3,377.8,384.2,387.6,392.7,396.2,396.1
173,Colombia,"Consumer Price Index, All items",PCPI_IX,5.967753,6.191108,6.372583,6.547079,6.679696,6.805333,6.89607,...,110.6031,111.4066,113.2623,115.1129,116.2593,117.7089,118.7032,119.3053,120.2736,121.5025

In [306]:
# Remove the columns "Indicator Name" and "Indicator Code" from pcpi_ix_data
pcpi_ix_data = pcpi_ix_data.drop(columns=['Indicator Name', 'Indicator Code'])
pcpi_ix_data.head()

,Country Name,1990M1,1990M2,1990M3,1990M4,1990M5,1990M6,1990M7,1990M8,1990M9,...,2021M11,2021M12,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8
17,Brazil,0.005410857,0.009508499,0.01734255,0.02003411,0.0215547,0.02408738,0.02719947,0.03070276,0.03512703,...,6075.69,6120.04,6153.09,6215.24,6315.93,6382.88,6412.88,6455.85,6411.95,NaN
30,France,66.42,66.56,66.72,67.09,67.19,67.18,67.2,67.64,68.12,...,107.64,107.85,108.12,108.94,110.49,110.97,111.72,112.55,112.87,113.29
104,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7659.2699399122,7728.99879117314,7841.08640403034,7954.55523691129,8131.17796924526,8331.52722236692,8432.65279081599,8506.69398844988,8601.91208943529,8702.17132815588
154,Honduras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,365,368.5,373,374.3,377.8,384.2,387.6,392.7,396.2,396.1
173,Colombia,5.967753,6.191108,6.372583,6.547079,6.679696,6.805333,6.89607,7.007748,7.175263,...,110.6031,111.4066,113.2623,115.1129,116.2593,117.7089,118.7032,119.3053,120.2736,121.5025

In [308]:
# Count null values per country (row) and sort from least to most
null_counts = pcpi_ix_data.isna().sum(axis=1).sort_values()

# Create a dataframe with results including country names
null_summary = pd.DataFrame({
    'Country': pcpi_ix_data.loc[null_counts.index, 'Country Name'].values,
    'Null Count': null_counts.values,
    'Total Columns': len(pcpi_ix_data.columns) - 1,  # -1 porque 'Country Name' não é um valor
    'Null Percentage': (null_counts.values / (len(pcpi_ix_data.columns) - 1) * 100).round(2)
})

print(f"Countries with null values - Sorted from least to most nulls:\n")
print(null_summary.to_string(index=False))

Countries with null values - Sorted from least to most nulls:

                                 Country  Null Count  Total Columns  Null Percentage
                                  France           0            392             0.00
                                Colombia           0            392             0.00
                                 Finland           0            392             0.00
                                 Germany           0            392             0.00
                                 Iceland           0            392             0.00
                                 Denmark           0            392             0.00
                                  Greece           0            392             0.00
                                 Austria           0            392             0.00
                                   Chile           0            392             0.00
                                 Belgium           0            392             0.00
                                 Hungary           0            392             0.00
                               Indonesia           0            392             0.00
                                  Israel           0            392             0.00
                                 Ireland           0            392             0.00
                       Slovenia, Rep. of           0            392             0.00
                                  Norway           0            392             0.00
                                   Italy           0            392             0.00
                                  Mexico           0            392             0.00
                              Luxembourg           0            392             0.00
                          Korea, Rep. of           0            392             0.00
                        Netherlands, The           0            392             0.00
                                Portugal           0            392             0.00
                         Poland, Rep. of           0            392             0.00
                                   Spain           0            392             0.00
                                  Turkey           0            392             0.00
                          United Kingdom           0            392             0.00
                           United States           0            392             0.00
                             Switzerland           0            392             0.00
                                  Canada           1            392             0.26
                              Costa Rica           1            392             0.26
                            South Africa           1            392             0.26
                                   Japan           1            392             0.26
                                Maldives           1            392             0.26
                                  Sweden           1            392             0.26
                                  Brazil           1            392             0.26
                                   India           3            392             0.77
                               Lithuania          11            392             2.81
                                  Latvia          12            392             3.06
                              Czech Rep.          12            392             3.06
                        Moldova, Rep. of          13            392             3.32
                             Slovak Rep.          13            392             3.32
                      Russian Federation          29            392             7.40
                   China, P.R.: Mainland          37            392             9.44
                                Bulgaria          60            392            15.31
                            Saudi Arabia          61            392            15.56
                                   Sudan          77            392            19.64
                           Côte d'Ivoire          85            392            21.68
                                   Haiti          86            392            21.94
                      West Bank and Gaza          86            392            21.94
                                   Ghana          94            392            23.98
                        Estonia, Rep. of          96            392            24.49
                                    Togo          99            392            25.26
                      China, P.R.: Macao         107            392            27.30
                          Dominican Rep.         110            392            28.06
                                 Burundi         110            392            28.06
                     Madagascar, Rep. of         112            392            28.57
                               Mauritius         114            392            29.08
                                 Jamaica         118            392            30.10
                                Honduras         119            392            30.36
                                  Cyprus         120            392            30.61
                     Trinidad and Tobago         122            392            31.12
                                 Romania         122            392            31.12
                                Malaysia         125            392            31.89
                                    Oman         133            392            33.93
                                Cambodia         133            392            33.93
      Ethiopia, The Federal Dem. Rep. of         136            392            34.69
                                 Senegal         136            392            34.69
                               St. Lucia         138            392            35.20
                     Antigua and Barbuda         140            392            35.71
                              Montserrat         140            392            35.71
                                 Grenada         140            392            35.71
          St. Vincent and the Grenadines         140            392            35.71
                                 Vietnam         143            392            36.48
            North Macedonia, Republic of         145            392            36.99
     Curaçao, Kingdom of the Netherlands         150            392            38.27
                                Dominica         151            392            38.52
                                  Panama         154            392            39.29
                             Kyrgyz Rep.         160            392            40.82
       Aruba, Kingdom of the Netherlands         162            392            41.33
                              Martinique         168            392            42.86
                                  Angola         168            392            42.86
                                  Rwanda         169            392            43.11
                   Iran, Islamic Rep. of         174            392            44.39
                  China, P.R.: Hong Kong         178            392            45.41
                     Mozambique, Rep. of         178            392            45.41
                     Azerbaijan, Rep. of         180            392            45.92
                                 Georgia         180            392            45.92
                         Kosovo, Rep. of         180            392            45.92
                                 Ukraine         180            392            45.92
                               Guatemala         180            392            45.92
                                   Samoa         181            392            46.17
                  Bosnia and Herzegovina         181            392            46.17
                        Belarus, Rep. of         181            392            46.17
                               Singapore         181            392            46.17
                                 Algeria         181            392            46.17
                     Lesotho, Kingdom of         182            392            46.43
                                 Ecuador         182            392            46.43
                                 Bolivia         182            392            46.43
                                 Uruguay         182            392            46.43
                               Nicaragua         182            392            46.43
                     Tajikistan, Rep. of         183            392            46.68
                                   Malta         183            392            46.68
                             Gambia, The         183            392            46.68
                                  Guyana         183            392            46.68
                                 Nigeria         184            392            46.94
                                 Namibia         184            392            46.94
                                 Tunisia         184            392            46.94
                  Lao People's Dem. Rep.         185            392            47.19
                                Paraguay         185            392            47.19
                              Cabo Verde         186            392            47.45
                          Congo, Rep. of         186            392            47.45
                        Croatia, Rep. of         187            392            47.70
                     St. Kitts and Nevis         188            392            47.96
                                Suriname         190            392            48.47
                                   Tonga         191            392            48.72
                                  Guinea         193            392            49.23
                                   Nepal         193            392            49.23
                                Mongolia         195            392            49.74
                     Kazakhstan, Rep. of         197            392            50.26
                    Central African Rep.         200            392            51.02
                                  Jordan         200            392            51.02
                         Serbia, Rep. of         204            392            52.04
                                 Albania         204            392            52.04
                            Sierra Leone         206            392            52.55
                                 Morocco         207            392            52.81
            Afghanistan, Islamic Rep. of         209            392            53.32
                    South Sudan, Rep. of         212            392            54.08
                    Eswatini, Kingdom of         214            392            54.59
                              Seychelles         214            392            54.59
                                   Benin         216            392            55.10
                                 Lebanon         216            392            55.10
                                Kiribati         221            392            56.38
                                Pakistan         222            392            56.63
                           Fiji, Rep. of         223            392            56.89
                    United Arab Emirates         228            392            58.16
                             El Salvador         229            392            58.42
                                 Liberia         233            392            59.44
                                  Belize         233            392            59.44
                                   Kenya         235            392            59.95
                                Zimbabwe         235            392            59.95
                                Thailand         240            392            61.22
                              Montenegro         240            392            61.22
                            Burkina Faso         240            392            61.22
                        Armenia, Rep. of         240            392            61.22
                                   Qatar         240            392            61.22
                              Bangladesh         241            392            61.48
                     Uzbekistan, Rep. of         241            392            61.48
                               Sri Lanka         241            392            61.48
                     Bahrain, Kingdom of         241            392            61.48
                                Botswana         241            392            61.48
                                Cameroon         242            392            61.73
                       Brunei Darussalam         242            392            61.73
                             Philippines         242            392            61.73
                                    Peru         242            392            61.73
                                  Kuwait         243            392            61.99
                                    Mali         243            392            61.99
                Tanzania, United Rep. of         243            392            61.99
                     Egypt, Arab Rep. of         244            392            62.24
                                  Zambia         244            392            62.24
                                    Chad         247            392            63.01
                                   Niger         248            392            63.27
                            Bahamas, The         248            392            63.27
                                Barbados         250            392            63.78
             Mauritania, Islamic Rep. of         250            392            63.78
                                  Malawi         251            392            64.03
                                  Uganda         257            392            65.56
              Equatorial Guinea, Rep. of         257            392            65.56
                                   Gabon         257            392            65.56
                                Djibouti         260            392            66.33
                                 Myanmar         261            392            66.58
                           Guinea-Bissau         263            392            67.09
               Timor-Leste, Dem. Rep. of         267            392            68.11
     São Tomé and Príncipe, Dem. Rep. of         276            392            70.41
                                  Bhutan         276            392            70.41
Sint Maarten, Kingdom of the Netherlands         278            392            70.92
                     San Marino, Rep. of         287            392            73.21
                         Solomon Islands         293            392            74.74
                                 Somalia         300            392            76.53
                                    Iraq         301            392            76.79
                           New Caledonia         307            392            78.32
                              Guadeloupe         308            392            78.57
          Venezuela, Rep. Bolivariana de         308            392            78.57
                               Argentina         326            392            83.16
                 Congo, Dem. Rep. of the         330            392            84.18
                          Yemen, Rep. of         331            392            84.44
                   Comoros, Union of the         334            392            85.20
                                   Libya         339            392            86.48
                        Syrian Arab Rep.         346            392            88.27
                          Nauru, Rep. of         348            392            88.78
                  British Virgin Islands         363            392            92.60