In [123]:
# %pip install pandas 
#import pandas as pd

dataset = pd.read_csv('CPITimeSeries.csv',low_memory=False)

In [124]:
# Filter the dataset to include only rows where "Country Name" contains "Poland"
dataset.columns
poland_data = dataset[dataset["Country Name"].str.contains("Poland", case=False, na=False)]
poland_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Attribute,1950M1,1950M2,1950M3,1950M4,1950M5,...,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8,Common Reference Period,Unnamed: 878
11286,"Slovenia, Rep. oPolandf",961,"Housing, Water, Electricity, Gas and Other Fue...",PCPIHAH_IX,Reference Period,NaN,NaN,NaN,NaN,NaN,...,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A,NaN,NaN
11298,"Poland, Rep. of",964,"Food and non-alcoholic beverages, Harmonized",PCPIHAF_IX,Status,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11299,"Poland, Rep. of",964,"Food and non-alcoholic beverages, Harmonized",PCPIHAF_IX,Reference Period,NaN,NaN,NaN,NaN,NaN,...,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A,NaN,NaN
11329,"Poland, Rep. of",964,"Miscellaneous goods and services, Harmonized, ...",PCPIHAO_PC_PP_PT,Value,NaN,NaN,NaN,NaN,NaN,...,1.57676348547718,0.245098039215684,0.651996740016298,1.29554655870445,1.11910471622702,0.316205533596842,0.315208825847117,1.57109190887668,NaN,NaN
11336,"Poland, Rep. of",964,"Education, Harmonized, Percentage change, Prev...",PCPIHAED_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,...,4.74547023295945,4.99139414802065,5.07308684436802,5.33104041272571,5.50300945829751,5.58419243986254,5.6701030927835,5.66523605150214,NaN,NaN

In [125]:
poland_data.shape

(177, 879)

In [126]:
print(poland_data.columns[poland_data.isnull().all()])

Index(['1950M1', '1950M2', '1950M3', '1950M4', '1950M5', '1950M6', '1950M7',
       '1950M8', '1950M9', '1950M10',
       ...
       '1988M4', '1988M5', '1988M6', '1988M7', '1988M8', '1988M9', '1988M10',
       '1988M11', '1988M12', 'Unnamed: 878'],
      dtype='str', length=469)

In [127]:
# Remove columns where all values are null 
poland_data = poland_data.dropna(axis=1, how='all')

In [128]:
poland_data["Country Name"].value_counts()

Country Name
Poland, Rep. of            176
Slovenia, Rep. oPolandf      1
Name: count, dtype: int64

In [129]:
poland_data["Country Code"].value_counts()

Country Code
964    176
961      1
Name: count, dtype: int64

In [130]:
poland_data.groupby("Country Code")["Country Name"] \
    .agg(['unique', 'count']) \
    .sort_values(by='count', ascending=False)

                                 unique  count
Country Code
964                   [Poland, Rep. of]    176
961           [Slovenia, Rep. oPolandf]      1

In [131]:
# Filter the dataset to include only rows corresponding to Poland
poland_data= poland_data [poland_data['Country Code'] == 964]

In [132]:
# Select only the columns whose names follow the "YYYYM#" format,
# meaning 4 digits for the year + 'M' + the month number.
year_columns = poland_data.columns[poland_data.columns.str.match(r'^\d{4}M\d+$')]
year_columns

Index(['1989M1', '1989M2', '1989M3', '1989M4', '1989M5', '1989M6', '1989M7',
       '1989M8', '1989M9', '1989M10',
       ...
       '2021M11', '2021M12', '2022M1', '2022M2', '2022M3', '2022M4', '2022M5',
       '2022M6', '2022M7', '2022M8'],
      dtype='str', length=404)

In [133]:
# Extract only the years (the first 4 digits of the column names)
years = year_columns.str[:4].astype(int)

# Show only the years that are out of order
# diff() < 0 indicates a decrease, meaning the order is not increasing
out_of_order_years = years[years.diff().fillna(1) < 0]  

print("Years out of order:")
print(out_of_order_years)

Years out of order:
Index([], dtype='int64')

In [134]:
# Extract year and month from the column names
year_month = year_columns.str.extract(r'(?P<Year>\d{4})M(?P<Month>\d{1,2})')
year_month['Year'] = year_month['Year'].astype(int)
year_month['Month'] = year_month['Month'].astype(int)

# Check for months that are out of order within each year
# diff() < 0 indicates a decrease in the sequence
months_out_of_order = year_month.groupby('Year')['Month'].apply(lambda x: x[x.diff().fillna(1) < 0])

print("Months out of order by year:")
print(months_out_of_order)

Months out of order by year:
Series([], Name: Month, dtype: int64)

In [135]:
poland_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Attribute,1989M1,1989M2,1989M3,1989M4,1989M5,...,2021M12,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8,Common Reference Period
11298,"Poland, Rep. of",964,"Food and non-alcoholic beverages, Harmonized",PCPIHAF_IX,Status,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11299,"Poland, Rep. of",964,"Food and non-alcoholic beverages, Harmonized",PCPIHAF_IX,Reference Period,NaN,NaN,NaN,NaN,NaN,...,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A,NaN
11329,"Poland, Rep. of",964,"Miscellaneous goods and services, Harmonized, ...",PCPIHAO_PC_PP_PT,Value,NaN,NaN,NaN,NaN,NaN,...,0.333055786844301,1.57676348547718,0.245098039215684,0.651996740016298,1.29554655870445,1.11910471622702,0.316205533596842,0.315208825847117,1.57109190887668,NaN
11336,"Poland, Rep. of",964,"Education, Harmonized, Percentage change, Prev...",PCPIHAED_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,...,4.23875432525952,4.74547023295945,4.99139414802065,5.07308684436802,5.33104041272571,5.50300945829751,5.58419243986254,5.6701030927835,5.66523605150214,NaN
11424,"Poland, Rep. of",964,"Miscellaneous goods and services, Harmonized, ...",PCPIHAO_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,...,2.64054514480408,4.25894378194208,3.89500423370026,4.92778249787595,6.19694397283531,6.93153000845309,7.26965342349958,7.33558178752108,8.74684608915055,NaN

In [136]:
# Keep only the columns with year >= 1990
year_columns_1990_onwards = year_columns[year_columns.str[:4].astype(int) >= 1990]

# Display the filtered columns
year_columns_1990_onwards

Index(['1990M1', '1990M2', '1990M3', '1990M4', '1990M5', '1990M6', '1990M7',
       '1990M8', '1990M9', '1990M10',
       ...
       '2021M11', '2021M12', '2022M1', '2022M2', '2022M3', '2022M4', '2022M5',
       '2022M6', '2022M7', '2022M8'],
      dtype='str', length=392)

In [137]:
poland_data = poland_data[["Indicator Name", "Indicator Code", "Attribute", "Common Reference Period"] + list(year_columns_1990_onwards)]

In [138]:
poland_data.head()

,Indicator Name,Indicator Code,Attribute,Common Reference Period,1990M1,1990M2,1990M3,1990M4,1990M5,1990M6,...,2021M11,2021M12,2022M1,2022M2,2022M3,2022M4,2022M5,2022M6,2022M7,2022M8
11298,"Food and non-alcoholic beverages, Harmonized",PCPIHAF_IX,Status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11299,"Food and non-alcoholic beverages, Harmonized",PCPIHAF_IX,Reference Period,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A,2015A
11329,"Miscellaneous goods and services, Harmonized, ...",PCPIHAO_PC_PP_PT,Value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.33416875522138,0.333055786844301,1.57676348547718,0.245098039215684,0.651996740016298,1.29554655870445,1.11910471622702,0.316205533596842,0.315208825847117,1.57109190887668
11336,"Education, Harmonized, Percentage change, Prev...",PCPIHAED_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.15224913494811,4.23875432525952,4.74547023295945,4.99139414802065,5.07308684436802,5.33104041272571,5.50300945829751,5.58419243986254,5.6701030927835,5.66523605150214
11424,"Miscellaneous goods and services, Harmonized, ...",PCPIHAO_PC_CP_A_PT,Value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.00171526586621,2.64054514480408,4.25894378194208,3.89500423370026,4.92778249787595,6.19694397283531,6.93153000845309,7.26965342349958,7.33558178752108,8.74684608915055

In [139]:
# Select only the year columns 
year_cols = year_columns_1990_onwards  

# Identify rows where all year columns are null 
all_null_rows = poland_data[year_cols].isnull().all(axis=1)

# Show how many rows would be removed
print("Number of rows with all NaN in year columns:", all_null_rows.sum())

Number of rows with all NaN in year columns: 0

In [140]:
# Calculate the proportion of non-null values in each row
non_null_ratio = poland_data[year_cols].notnull().mean(axis=1)

# Identify rows with less than 20% of values
high_null_rows = non_null_ratio < 0.2

# Show how many rows have >80% NaN
print("Number of rows with more than 80% NaN in year columns:", high_null_rows.sum())

# Remove these rows from the dataset
poland_data = poland_data[~high_null_rows]

Number of rows with more than 80% NaN in year columns: 25